FROM timeloveboy/moedocker
MAINTAINER timeloveboy(734991033@qq.com)
RUN apt-get update
RUN apt-get install -y \
  libleptonica-dev \
  libtesseract3 \
  libtesseract-dev \
  tesseract-ocr \
  tesseract-ocr-eng

