FROM timeloveboy/jdk8
MAINTAINER timeloveboy(734991033@qq.com)
# 非交互式
ADD install.sh install.sh
RUN sh install.sh
ENV M2_HOME /opt/maven
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jdk8/bin:/opt/maven/bin

