# Default values for httpreturn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: timeloveboy/httpreturn
  tag: latest
  pullPolicy: IfNotPresent
  port: 9000

service:
  type: LoadBalancer
  port: 80


ingress:
  enabled: false
  annotations: {}

  path: /
  hosts:
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
