FROM timeloveboy/moedocker
MAINTAINER timeloveboy(734991033@qq.com)

ADD installgo.sh installgo.sh
RUN sh installgo.sh
ENV GOROOT /opt/go
ENV GOPATH /GOPATH
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/go/bin
