FROM timeloveboy/moedocker
MAINTAINER timeloveboy(734991033@qq.com)
ADD installjdk.sh installjdk.sh
RUN sh installjdk.sh
ENV JAVA_HOME /opt/jdk8
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jdk8/bin

