apiVersion: v1
kind: Pod
metadata:
  name: return
  labels:
    app: return
spec:
  containers:
    - name: return
      image: timeloveboy/httpreturn
      ports:
      - containerPort: 9000
      command: [ httpreturn , im1 ]